// <auto-generated />
using System;
using Auth.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Auth.Domain.Migrations
{
    [DbContext(typeof(DocAIAuthContext))]
    [Migration("20250618103104_migration1")]
    partial class migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auth.Domain.Models.ActiveKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ActiveKeys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50b64957-bae3-4377-aa7a-fee36d25ccd6"),
                            ActivationCode = "P4rBZtdXa5YvEGJNmKLcQq7RfW9HU61o",
                            RoleName = "Editor"
                        },
                        new
                        {
                            Id = new Guid("65de7f7d-0bcc-4cdf-bd8c-f8d1ac290cd8"),
                            ActivationCode = "zXYmN7pLcVTEqF59jKADrCbhQuU630aw",
                            RoleName = "Manager"
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            CreateAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(3015),
                            Description = "DepartentA",
                            Name = "DepartentA",
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(3134)
                        },
                        new
                        {
                            Id = new Guid("86deff8b-cb4b-4daf-88d4-6f366b051836"),
                            CreateAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(3215),
                            Description = "DepartmentB",
                            Name = "DepartmentB",
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(3215)
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.DepartmentRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDepartmentHead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("DepartmentRolePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("79f5ecd3-50a3-46af-8ce8-f258f00efd4a"),
                            CreatAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(6689),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            IsDepartmentHead = true,
                            PermissionId = new Guid("e72214a0-24bc-471a-aca5-d897f4da0aad"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb"),
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(6776),
                            UserId = new Guid("595dd357-aaec-455e-9fa7-4fc88d4b819c")
                        },
                        new
                        {
                            Id = new Guid("e055e80e-294b-4707-afa9-5bc2a412218c"),
                            CreatAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(6854),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            IsDepartmentHead = true,
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb"),
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(6854),
                            UserId = new Guid("595dd357-aaec-455e-9fa7-4fc88d4b819c")
                        },
                        new
                        {
                            Id = new Guid("65a1468f-753e-46be-ad7c-31ae60ed5a65"),
                            CreatAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(6858),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            IsDepartmentHead = false,
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136"),
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(6858),
                            UserId = new Guid("5c49c1cb-719e-42eb-8028-f2eb3eaea4cd")
                        },
                        new
                        {
                            Id = new Guid("3709cb77-7539-4423-9f97-a1dc49e155ab"),
                            CreatAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(6861),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            IsDepartmentHead = false,
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f"),
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(6862),
                            UserId = new Guid("fd05266c-baf5-49bb-a846-554461bcc411")
                        },
                        new
                        {
                            Id = new Guid("ab0d0397-a755-4e55-8368-0d3ddc026727"),
                            CreatAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(6865),
                            DepartmentId = new Guid("86deff8b-cb4b-4daf-88d4-6f366b051836"),
                            IsDepartmentHead = false,
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f"),
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(6865),
                            UserId = new Guid("fd05266c-baf5-49bb-a846-554461bcc411")
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3796cdb0-7c0a-4cc6-a757-883fe1865fb6"),
                            CreateAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(9111),
                            Description = "Quyền xem mọi tài liệu trong hệ thống ",
                            Name = "VIEW_ANY_DOCUMENT",
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(9210)
                        },
                        new
                        {
                            Id = new Guid("e72214a0-24bc-471a-aca5-d897f4da0aad"),
                            CreateAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(9293),
                            Description = "Quyền xem tài liệu thuộc phòng ban của mình.",
                            Name = "VIEW_OWN_DEPARTMENT_DOCUMENT",
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(9294)
                        },
                        new
                        {
                            Id = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            CreateAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(9295),
                            Description = "Quyền xem tài liệu của mình.",
                            Name = "VIEW_DEPARTMENT_DOCUMENT",
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 912, DateTimeKind.Utc).AddTicks(9296)
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f"),
                            CreateAt = new DateTime(2025, 6, 18, 10, 31, 3, 913, DateTimeKind.Utc).AddTicks(1517),
                            Description = "Member",
                            RoleName = "Member",
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 913, DateTimeKind.Utc).AddTicks(1608)
                        },
                        new
                        {
                            Id = new Guid("a996692c-1f5e-4458-8dcf-c2494a47b6d6"),
                            CreateAt = new DateTime(2025, 6, 18, 10, 31, 3, 913, DateTimeKind.Utc).AddTicks(1698),
                            Description = "Admin",
                            RoleName = "Admin",
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 913, DateTimeKind.Utc).AddTicks(1699)
                        },
                        new
                        {
                            Id = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb"),
                            CreateAt = new DateTime(2025, 6, 18, 10, 31, 3, 913, DateTimeKind.Utc).AddTicks(1700),
                            Description = "Manager",
                            RoleName = "Manager",
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 913, DateTimeKind.Utc).AddTicks(1701)
                        },
                        new
                        {
                            Id = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136"),
                            CreateAt = new DateTime(2025, 6, 18, 10, 31, 3, 913, DateTimeKind.Utc).AddTicks(1702),
                            Description = "Editor",
                            RoleName = "Editor",
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 913, DateTimeKind.Utc).AddTicks(1702)
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7bede109-ee65-4aa5-ac38-5bb9b571ebf2"),
                            PermissionId = new Guid("3796cdb0-7c0a-4cc6-a757-883fe1865fb6"),
                            RoleId = new Guid("a996692c-1f5e-4458-8dcf-c2494a47b6d6")
                        },
                        new
                        {
                            Id = new Guid("d6afded8-c5bc-4062-92c9-b72edac28d90"),
                            PermissionId = new Guid("e72214a0-24bc-471a-aca5-d897f4da0aad"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb")
                        },
                        new
                        {
                            Id = new Guid("ea5b9fe4-f490-4792-a425-dfb853f7dce1"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f")
                        },
                        new
                        {
                            Id = new Guid("66e1e900-ba76-4657-8cf0-613cb064793e"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136")
                        },
                        new
                        {
                            Id = new Guid("0660d80c-3d49-4249-96ef-875d588b1c65"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb")
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TwoFactorMethod")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13d466ed-8a2d-414d-88c0-9c7adcac2616"),
                            CreatAt = new DateTime(2025, 6, 18, 10, 31, 3, 939, DateTimeKind.Utc).AddTicks(6915),
                            Email = "admin@gmail.com",
                            FullName = "Admin",
                            Password = "q2JeW34Zf0qgo5Ra6+iBTp0R5u1BvoRrRWEWQRmKK9j4TV+hPSc3E3RGV5zm7Elc",
                            Phone = "0847911068",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 939, DateTimeKind.Utc).AddTicks(7055),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("595dd357-aaec-455e-9fa7-4fc88d4b819c"),
                            CreatAt = new DateTime(2025, 6, 18, 10, 31, 3, 957, DateTimeKind.Utc).AddTicks(9247),
                            Email = "manager@gmail.com",
                            FullName = "Manager",
                            Password = "QXB0X/Yqm3s2WhU2A0tKMh7ECPNhKJXuqzwe2vPRyLFkj2vzPQRnVvkUYPq1VERq",
                            Phone = "0123456789",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 957, DateTimeKind.Utc).AddTicks(9252),
                            UserName = "manager"
                        },
                        new
                        {
                            Id = new Guid("fd05266c-baf5-49bb-a846-554461bcc411"),
                            CreatAt = new DateTime(2025, 6, 18, 10, 31, 3, 975, DateTimeKind.Utc).AddTicks(9534),
                            Email = "member@gmail.com",
                            FullName = "Member",
                            Password = "YddDKQDbGZYjGznmnLXnZTHkX7lxFX4pUjyVJmaobVsQxP5BANwidpyf4SeYB3iQ",
                            Phone = "0123456789",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 975, DateTimeKind.Utc).AddTicks(9540),
                            UserName = "member"
                        },
                        new
                        {
                            Id = new Guid("5c49c1cb-719e-42eb-8028-f2eb3eaea4cd"),
                            CreatAt = new DateTime(2025, 6, 18, 10, 31, 3, 994, DateTimeKind.Utc).AddTicks(4293),
                            Email = "editor@gmail.com",
                            FullName = "Member1",
                            Password = "I1SWkV6xjXmynG61xnc37kNCzYlJ/A4hpgmxMK70eDjmB9GGXHUfY/f0dinwAu9h",
                            Phone = "0123456789",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 6, 18, 10, 31, 3, 994, DateTimeKind.Utc).AddTicks(4298),
                            UserName = "editor"
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.UserDepartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDepartmentHead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDepartments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2e1487eb-81a8-4925-8bac-7facd7277b71"),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            IsDepartmentHead = true,
                            UserId = new Guid("595dd357-aaec-455e-9fa7-4fc88d4b819c")
                        },
                        new
                        {
                            Id = new Guid("dea22e99-739b-43cc-b7ed-865a481a6412"),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            IsDepartmentHead = false,
                            UserId = new Guid("5c49c1cb-719e-42eb-8028-f2eb3eaea4cd")
                        },
                        new
                        {
                            Id = new Guid("fab49049-4972-4070-9d69-1aef5f0081c8"),
                            DepartmentId = new Guid("86deff8b-cb4b-4daf-88d4-6f366b051836"),
                            IsDepartmentHead = false,
                            UserId = new Guid("fd05266c-baf5-49bb-a846-554461bcc411")
                        },
                        new
                        {
                            Id = new Guid("68385e8b-e03a-414a-941f-0e889f6cea64"),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            IsDepartmentHead = false,
                            UserId = new Guid("fd05266c-baf5-49bb-a846-554461bcc411")
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c978f375-1a64-413a-88c5-a89456490df9"),
                            RoleId = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136"),
                            UserId = new Guid("5c49c1cb-719e-42eb-8028-f2eb3eaea4cd")
                        },
                        new
                        {
                            Id = new Guid("3e0809c4-5432-41b3-9161-cabf967a128e"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb"),
                            UserId = new Guid("595dd357-aaec-455e-9fa7-4fc88d4b819c")
                        },
                        new
                        {
                            Id = new Guid("60a9dc18-e62e-4e7c-aaf6-f10713851342"),
                            RoleId = new Guid("a996692c-1f5e-4458-8dcf-c2494a47b6d6"),
                            UserId = new Guid("13d466ed-8a2d-414d-88c0-9c7adcac2616")
                        },
                        new
                        {
                            Id = new Guid("b12b0456-a76a-436b-a7a2-8b3c179e7a50"),
                            RoleId = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f"),
                            UserId = new Guid("fd05266c-baf5-49bb-a846-554461bcc411")
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.DepartmentRolePermission", b =>
                {
                    b.HasOne("Auth.Domain.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Permission");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Auth.Domain.Models.RolePermission", b =>
                {
                    b.HasOne("Auth.Domain.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Auth.Domain.Models.UserDepartment", b =>
                {
                    b.HasOne("Auth.Domain.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.User", "User")
                        .WithMany("UserDepartments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Auth.Domain.Models.UserRole", b =>
                {
                    b.HasOne("Auth.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Auth.Domain.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Auth.Domain.Models.User", b =>
                {
                    b.Navigation("UserDepartments");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
