// <auto-generated />
using System;
using Auth.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Auth.Domain.Migrations
{
    [DbContext(typeof(DocAIAuthContext))]
    [Migration("20250613112458_migration3")]
    partial class migration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auth.Domain.Models.ActiveKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ActiveKeys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50b64957-bae3-4377-aa7a-fee36d25ccd6"),
                            ActivationCode = "P4rBZtdXa5YvEGJNmKLcQq7RfW9HU61o",
                            RoleName = "Editor"
                        },
                        new
                        {
                            Id = new Guid("65de7f7d-0bcc-4cdf-bd8c-f8d1ac290cd8"),
                            ActivationCode = "zXYmN7pLcVTEqF59jKADrCbhQuU630aw",
                            RoleName = "Manager"
                        },
                        new
                        {
                            Id = new Guid("23deb45b-705a-4c86-be05-61201fcac8be"),
                            ActivationCode = "g1UHzv7McAbpRKeYwXd29fQsTNLqJo5C",
                            RoleName = "Director"
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Auth.Domain.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3796cdb0-7c0a-4cc6-a757-883fe1865fb6"),
                            CreateAt = new DateTime(2025, 6, 13, 11, 24, 57, 766, DateTimeKind.Utc).AddTicks(9356),
                            Description = "Quyền xem mọi tài liệu trong hệ thống ",
                            Name = "VIEW_ANY_DOCUMENT",
                            UpdateAt = new DateTime(2025, 6, 13, 11, 24, 57, 766, DateTimeKind.Utc).AddTicks(9463)
                        },
                        new
                        {
                            Id = new Guid("e72214a0-24bc-471a-aca5-d897f4da0aad"),
                            CreateAt = new DateTime(2025, 6, 13, 11, 24, 57, 766, DateTimeKind.Utc).AddTicks(9543),
                            Description = "Quyền xem tài liệu thuộc phòng ban của mình.",
                            Name = "VIEW_OWN_DEPARTMENT_DOCUMENT",
                            UpdateAt = new DateTime(2025, 6, 13, 11, 24, 57, 766, DateTimeKind.Utc).AddTicks(9544)
                        },
                        new
                        {
                            Id = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            CreateAt = new DateTime(2025, 6, 13, 11, 24, 57, 766, DateTimeKind.Utc).AddTicks(9545),
                            Description = "Quyền xem tài liệu của mình.",
                            Name = "VIEW_DEPARTMENT_DOCUMENT",
                            UpdateAt = new DateTime(2025, 6, 13, 11, 24, 57, 766, DateTimeKind.Utc).AddTicks(9546)
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f"),
                            CreateAt = new DateTime(2025, 6, 13, 11, 24, 57, 767, DateTimeKind.Utc).AddTicks(2108),
                            Description = "Member",
                            RoleName = "Member",
                            UpdateAt = new DateTime(2025, 6, 13, 11, 24, 57, 767, DateTimeKind.Utc).AddTicks(2198)
                        },
                        new
                        {
                            Id = new Guid("a996692c-1f5e-4458-8dcf-c2494a47b6d6"),
                            CreateAt = new DateTime(2025, 6, 13, 11, 24, 57, 767, DateTimeKind.Utc).AddTicks(2276),
                            Description = "Admin",
                            RoleName = "Admin",
                            UpdateAt = new DateTime(2025, 6, 13, 11, 24, 57, 767, DateTimeKind.Utc).AddTicks(2276)
                        },
                        new
                        {
                            Id = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb"),
                            CreateAt = new DateTime(2025, 6, 13, 11, 24, 57, 767, DateTimeKind.Utc).AddTicks(2278),
                            Description = "Manager",
                            RoleName = "Manager",
                            UpdateAt = new DateTime(2025, 6, 13, 11, 24, 57, 767, DateTimeKind.Utc).AddTicks(2278)
                        },
                        new
                        {
                            Id = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136"),
                            CreateAt = new DateTime(2025, 6, 13, 11, 24, 57, 767, DateTimeKind.Utc).AddTicks(2280),
                            Description = "Editor",
                            RoleName = "Editor",
                            UpdateAt = new DateTime(2025, 6, 13, 11, 24, 57, 767, DateTimeKind.Utc).AddTicks(2280)
                        },
                        new
                        {
                            Id = new Guid("9ede53c4-e407-492c-8dfe-d87185575cf0"),
                            CreateAt = new DateTime(2025, 6, 13, 11, 24, 57, 767, DateTimeKind.Utc).AddTicks(2282),
                            Description = "Director",
                            RoleName = "Director",
                            UpdateAt = new DateTime(2025, 6, 13, 11, 24, 57, 767, DateTimeKind.Utc).AddTicks(2282)
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff7cb06c-ceb7-4ee9-b59e-a1c747d371f6"),
                            PermissionId = new Guid("3796cdb0-7c0a-4cc6-a757-883fe1865fb6"),
                            RoleId = new Guid("9ede53c4-e407-492c-8dfe-d87185575cf0")
                        },
                        new
                        {
                            Id = new Guid("826f4cea-78ec-4aa9-9bef-52474b1b87c5"),
                            PermissionId = new Guid("3796cdb0-7c0a-4cc6-a757-883fe1865fb6"),
                            RoleId = new Guid("a996692c-1f5e-4458-8dcf-c2494a47b6d6")
                        },
                        new
                        {
                            Id = new Guid("145ecec9-7832-4c8a-9ec1-76c4276ffc81"),
                            PermissionId = new Guid("e72214a0-24bc-471a-aca5-d897f4da0aad"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb")
                        },
                        new
                        {
                            Id = new Guid("e2a0273b-875d-4de9-a224-525a10d0325a"),
                            PermissionId = new Guid("e72214a0-24bc-471a-aca5-d897f4da0aad"),
                            RoleId = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136")
                        },
                        new
                        {
                            Id = new Guid("038e1f74-4cb4-439d-95bb-72392eb287b4"),
                            PermissionId = new Guid("e72214a0-24bc-471a-aca5-d897f4da0aad"),
                            RoleId = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f")
                        },
                        new
                        {
                            Id = new Guid("c735035b-6a25-4687-aa75-1b053b8378c9"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136")
                        },
                        new
                        {
                            Id = new Guid("51badb5e-f95e-4e31-aaac-5486f7d0c70f"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb")
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TwoFactorMethod")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13d466ed-8a2d-414d-88c0-9c7adcac2616"),
                            CreatAt = new DateTime(2025, 6, 13, 11, 24, 57, 791, DateTimeKind.Utc).AddTicks(3833),
                            Email = "admin@gmail.com",
                            FullName = "Admin",
                            Password = "baXt++NEsqjRMW2jx4k5srt+YMOLG3JVG7+9abANDw0HyoBVUB/vcb2FXjMDPXqJ",
                            Phone = "0847911068",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 6, 13, 11, 24, 57, 791, DateTimeKind.Utc).AddTicks(3973),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("a9df371e-9249-47b8-83ce-8cd940140b9b"),
                            CreatAt = new DateTime(2025, 6, 13, 11, 24, 57, 809, DateTimeKind.Utc).AddTicks(9018),
                            Email = "director@gmail.com",
                            FullName = "Director",
                            Password = "58YULs2gyUTVDsWupFKewNrOySTOcSSNKIW6SsZ11071zKmb53sT3kGFCBXDSKHW",
                            Phone = "0123456789",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 6, 13, 11, 24, 57, 809, DateTimeKind.Utc).AddTicks(9025),
                            UserName = "director"
                        },
                        new
                        {
                            Id = new Guid("595dd357-aaec-455e-9fa7-4fc88d4b819c"),
                            CreatAt = new DateTime(2025, 6, 13, 11, 24, 57, 828, DateTimeKind.Utc).AddTicks(4158),
                            Email = "manager@gmail.com",
                            FullName = "Manager",
                            Password = "h6ks7YC/YuaIJHRDV9XsCcIvXcdC/MOO281YjOfPovHjwtMAX6Z6a2OfgNhJ6YY1",
                            Phone = "0123456789",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 6, 13, 11, 24, 57, 828, DateTimeKind.Utc).AddTicks(4163),
                            UserName = "manager"
                        },
                        new
                        {
                            Id = new Guid("fd05266c-baf5-49bb-a846-554461bcc411"),
                            CreatAt = new DateTime(2025, 6, 13, 11, 24, 57, 847, DateTimeKind.Utc).AddTicks(4112),
                            Email = "member@gmail.com",
                            FullName = "Member",
                            Password = "dssDadhplLlg/i2sqAP7PkUQi2JZsumEIrhS4H63PADxD2YzqF3vl+rLM2mEHLs7",
                            Phone = "0123456789",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 6, 13, 11, 24, 57, 847, DateTimeKind.Utc).AddTicks(4119),
                            UserName = "member"
                        },
                        new
                        {
                            Id = new Guid("5c49c1cb-719e-42eb-8028-f2eb3eaea4cd"),
                            CreatAt = new DateTime(2025, 6, 13, 11, 24, 57, 865, DateTimeKind.Utc).AddTicks(9614),
                            Email = "editor@gmail.com",
                            FullName = "Member1",
                            Password = "gf+67eSJisOBAHM+ouJNh+LonniztEwWg9Tgw3QgiW9FneQVVK/dHjibWXh2kovW",
                            Phone = "0123456789",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 6, 13, 11, 24, 57, 865, DateTimeKind.Utc).AddTicks(9619),
                            UserName = "editor"
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.UserDepartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDepartmentHead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("departmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("departmentId");

                    b.HasIndex("userId");

                    b.ToTable("UserDepartments");
                });

            modelBuilder.Entity("Auth.Domain.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c0e82ed-444b-4474-aefe-1ea7c82a92fa"),
                            RoleId = new Guid("9ede53c4-e407-492c-8dfe-d87185575cf0"),
                            UserId = new Guid("a9df371e-9249-47b8-83ce-8cd940140b9b")
                        },
                        new
                        {
                            Id = new Guid("0f0b8157-b313-4ff9-8e35-6ee3452522de"),
                            RoleId = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136"),
                            UserId = new Guid("5c49c1cb-719e-42eb-8028-f2eb3eaea4cd")
                        },
                        new
                        {
                            Id = new Guid("177b2978-e8ee-4cf0-b75f-4ec5c11e16e5"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb"),
                            UserId = new Guid("595dd357-aaec-455e-9fa7-4fc88d4b819c")
                        },
                        new
                        {
                            Id = new Guid("891e20a1-1d68-46b0-8019-8f7edd11795c"),
                            RoleId = new Guid("a996692c-1f5e-4458-8dcf-c2494a47b6d6"),
                            UserId = new Guid("13d466ed-8a2d-414d-88c0-9c7adcac2616")
                        },
                        new
                        {
                            Id = new Guid("6864d47f-f5cf-4b66-837d-3a7cd28639cd"),
                            RoleId = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f"),
                            UserId = new Guid("fd05266c-baf5-49bb-a846-554461bcc411")
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.RolePermission", b =>
                {
                    b.HasOne("Auth.Domain.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Auth.Domain.Models.UserDepartment", b =>
                {
                    b.HasOne("Auth.Domain.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("departmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.User", "User")
                        .WithMany("UserDepartments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Auth.Domain.Models.UserRole", b =>
                {
                    b.HasOne("Auth.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Auth.Domain.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Auth.Domain.Models.User", b =>
                {
                    b.Navigation("UserDepartments");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
