// <auto-generated />
using System;
using Auth.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Auth.Domain.Migrations
{
    [DbContext(typeof(DocAIAuthContext))]
    [Migration("20250703100337_migration4")]
    partial class migration4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auth.Domain.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            CreateAt = new DateTime(2025, 7, 3, 10, 3, 36, 648, DateTimeKind.Utc).AddTicks(8576),
                            Description = "DepartentA",
                            Name = "DepartentA",
                            UpdateAt = new DateTime(2025, 7, 3, 10, 3, 36, 648, DateTimeKind.Utc).AddTicks(8683)
                        },
                        new
                        {
                            Id = new Guid("d8854d21-8fae-46aa-b51b-0de060b92ee3"),
                            CreateAt = new DateTime(2025, 7, 3, 10, 3, 36, 648, DateTimeKind.Utc).AddTicks(8765),
                            Description = "Company",
                            Name = "Company",
                            UpdateAt = new DateTime(2025, 7, 3, 10, 3, 36, 648, DateTimeKind.Utc).AddTicks(8766)
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3796cdb0-7c0a-4cc6-a757-883fe1865fb6"),
                            CreateAt = new DateTime(2025, 7, 3, 10, 3, 36, 649, DateTimeKind.Utc).AddTicks(6550),
                            Description = "Quyền xem mọi tài liệu trong hệ thống ",
                            Name = "VIEW_ANY_DOCUMENT",
                            UpdateAt = new DateTime(2025, 7, 3, 10, 3, 36, 649, DateTimeKind.Utc).AddTicks(6650)
                        },
                        new
                        {
                            Id = new Guid("e72214a0-24bc-471a-aca5-d897f4da0aad"),
                            CreateAt = new DateTime(2025, 7, 3, 10, 3, 36, 649, DateTimeKind.Utc).AddTicks(6727),
                            Description = "Quyền xem tài liệu thuộc phòng ban của mình.",
                            Name = "VIEW_OWN_DEPARTMENT_DOCUMENT",
                            UpdateAt = new DateTime(2025, 7, 3, 10, 3, 36, 649, DateTimeKind.Utc).AddTicks(6728)
                        },
                        new
                        {
                            Id = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            CreateAt = new DateTime(2025, 7, 3, 10, 3, 36, 649, DateTimeKind.Utc).AddTicks(6730),
                            Description = "Quyền xem tài liệu của mình.",
                            Name = "VIEW_DEPARTMENT_DOCUMENT",
                            UpdateAt = new DateTime(2025, 7, 3, 10, 3, 36, 649, DateTimeKind.Utc).AddTicks(6730)
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f"),
                            CreateAt = new DateTime(2025, 7, 3, 10, 3, 36, 649, DateTimeKind.Utc).AddTicks(9090),
                            Description = "Member",
                            RoleName = "Member",
                            UpdateAt = new DateTime(2025, 7, 3, 10, 3, 36, 649, DateTimeKind.Utc).AddTicks(9179)
                        },
                        new
                        {
                            Id = new Guid("a996692c-1f5e-4458-8dcf-c2494a47b6d6"),
                            CreateAt = new DateTime(2025, 7, 3, 10, 3, 36, 649, DateTimeKind.Utc).AddTicks(9253),
                            Description = "Admin",
                            RoleName = "Admin",
                            UpdateAt = new DateTime(2025, 7, 3, 10, 3, 36, 649, DateTimeKind.Utc).AddTicks(9253)
                        },
                        new
                        {
                            Id = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb"),
                            CreateAt = new DateTime(2025, 7, 3, 10, 3, 36, 649, DateTimeKind.Utc).AddTicks(9255),
                            Description = "Manager",
                            RoleName = "Manager",
                            UpdateAt = new DateTime(2025, 7, 3, 10, 3, 36, 649, DateTimeKind.Utc).AddTicks(9255)
                        },
                        new
                        {
                            Id = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136"),
                            CreateAt = new DateTime(2025, 7, 3, 10, 3, 36, 649, DateTimeKind.Utc).AddTicks(9257),
                            Description = "Editor",
                            RoleName = "Editor",
                            UpdateAt = new DateTime(2025, 7, 3, 10, 3, 36, 649, DateTimeKind.Utc).AddTicks(9257)
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e929753e-7b49-4896-88a6-6bcc70d05427"),
                            PermissionId = new Guid("3796cdb0-7c0a-4cc6-a757-883fe1865fb6"),
                            RoleId = new Guid("a996692c-1f5e-4458-8dcf-c2494a47b6d6")
                        },
                        new
                        {
                            Id = new Guid("c58d11aa-99ef-4154-bf8c-ef68bc76af63"),
                            PermissionId = new Guid("e72214a0-24bc-471a-aca5-d897f4da0aad"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb")
                        },
                        new
                        {
                            Id = new Guid("8160062d-42a6-496f-ac39-facbdf2c414b"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f")
                        },
                        new
                        {
                            Id = new Guid("2e29a4df-916e-4ce7-ac3b-ea5cf1655f7a"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136")
                        },
                        new
                        {
                            Id = new Guid("466b8527-2b48-4213-804b-d4b8703e2912"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb")
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TwoFactorMethod")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13d466ed-8a2d-414d-88c0-9c7adcac2616"),
                            CreatAt = new DateTime(2025, 7, 3, 10, 3, 36, 674, DateTimeKind.Utc).AddTicks(6407),
                            DepartmentId = new Guid("d8854d21-8fae-46aa-b51b-0de060b92ee3"),
                            Email = "admin@gmail.com",
                            FullName = "Admin",
                            Password = "eYT2WXQtT+wDZ0LZuMxAnMeLPWVKJrQiTtQ3hX6sNR0tNAsWIK2iTJ6MVGrI4o0L",
                            Phone = "0847911068",
                            RoleId = new Guid("a996692c-1f5e-4458-8dcf-c2494a47b6d6"),
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 7, 3, 10, 3, 36, 674, DateTimeKind.Utc).AddTicks(6614),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("595dd357-aaec-455e-9fa7-4fc88d4b819c"),
                            CreatAt = new DateTime(2025, 7, 3, 10, 3, 36, 694, DateTimeKind.Utc).AddTicks(8096),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            Email = "manager@gmail.com",
                            FullName = "Manager",
                            Password = "lnSxJu92BNFXEnzlPb+57IiLUEKgcHWSXjIwTk/gY1oslwYAmIfYWS7lNbvS6zrz",
                            Phone = "0123456789",
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb"),
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 7, 3, 10, 3, 36, 694, DateTimeKind.Utc).AddTicks(8103),
                            UserName = "manager"
                        },
                        new
                        {
                            Id = new Guid("fd05266c-baf5-49bb-a846-554461bcc411"),
                            CreatAt = new DateTime(2025, 7, 3, 10, 3, 36, 713, DateTimeKind.Utc).AddTicks(6018),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            Email = "member@gmail.com",
                            FullName = "Member",
                            Password = "87yKBhE8FyCr/WEaJZsx0zyPXayCnk3uBiSVyFd+vnVJpXVTu8wDiad/WaoE8Bax",
                            Phone = "0123456789",
                            RoleId = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f"),
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 7, 3, 10, 3, 36, 713, DateTimeKind.Utc).AddTicks(6026),
                            UserName = "member"
                        },
                        new
                        {
                            Id = new Guid("5c49c1cb-719e-42eb-8028-f2eb3eaea4cd"),
                            CreatAt = new DateTime(2025, 7, 3, 10, 3, 36, 732, DateTimeKind.Utc).AddTicks(4177),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            Email = "editor@gmail.com",
                            FullName = "Editor",
                            Password = "g8MNPYv3YpsR7rBvesb9XMVEhpO5eluy5eW4zP1GGdzV9p0UYGg0HVbVYfGZayrp",
                            Phone = "0123456789",
                            RoleId = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136"),
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 7, 3, 10, 3, 36, 732, DateTimeKind.Utc).AddTicks(4185),
                            UserName = "editor"
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.RolePermission", b =>
                {
                    b.HasOne("Auth.Domain.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Auth.Domain.Models.User", b =>
                {
                    b.HasOne("Auth.Domain.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Auth.Domain.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
