// <auto-generated />
using System;
using Auth.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Auth.Domain.Migrations
{
    [DbContext(typeof(DocAIAuthContext))]
    [Migration("20250618111326_migration2")]
    partial class migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auth.Domain.Models.ActiveKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ActiveKeys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50b64957-bae3-4377-aa7a-fee36d25ccd6"),
                            ActivationCode = "P4rBZtdXa5YvEGJNmKLcQq7RfW9HU61o",
                            RoleName = "Editor"
                        },
                        new
                        {
                            Id = new Guid("65de7f7d-0bcc-4cdf-bd8c-f8d1ac290cd8"),
                            ActivationCode = "zXYmN7pLcVTEqF59jKADrCbhQuU630aw",
                            RoleName = "Manager"
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            CreateAt = new DateTime(2025, 6, 18, 11, 13, 26, 220, DateTimeKind.Utc).AddTicks(9563),
                            Description = "DepartentA",
                            Name = "DepartentA",
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 220, DateTimeKind.Utc).AddTicks(9701)
                        },
                        new
                        {
                            Id = new Guid("86deff8b-cb4b-4daf-88d4-6f366b051836"),
                            CreateAt = new DateTime(2025, 6, 18, 11, 13, 26, 220, DateTimeKind.Utc).AddTicks(9785),
                            Description = "DepartmentB",
                            Name = "DepartmentB",
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 220, DateTimeKind.Utc).AddTicks(9786)
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.DepartmentRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("DepartmentRolePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e55561aa-7c0a-4dc8-844c-9a24acb678c4"),
                            CreatAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(3203),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            PermissionId = new Guid("e72214a0-24bc-471a-aca5-d897f4da0aad"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb"),
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(3294),
                            UserId = new Guid("595dd357-aaec-455e-9fa7-4fc88d4b819c")
                        },
                        new
                        {
                            Id = new Guid("a716fb6a-dc2a-417e-987f-006f7c254e96"),
                            CreatAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(3377),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb"),
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(3377),
                            UserId = new Guid("595dd357-aaec-455e-9fa7-4fc88d4b819c")
                        },
                        new
                        {
                            Id = new Guid("f6528a1f-2104-41f3-b70d-b71bf9930639"),
                            CreatAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(3381),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136"),
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(3381),
                            UserId = new Guid("5c49c1cb-719e-42eb-8028-f2eb3eaea4cd")
                        },
                        new
                        {
                            Id = new Guid("5976f05f-2a3e-4f94-84f7-7178c8a1d572"),
                            CreatAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(3391),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f"),
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(3392),
                            UserId = new Guid("fd05266c-baf5-49bb-a846-554461bcc411")
                        },
                        new
                        {
                            Id = new Guid("bf3efb31-c414-4913-84fd-12c9443a8f53"),
                            CreatAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(3395),
                            DepartmentId = new Guid("86deff8b-cb4b-4daf-88d4-6f366b051836"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f"),
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(3395),
                            UserId = new Guid("fd05266c-baf5-49bb-a846-554461bcc411")
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3796cdb0-7c0a-4cc6-a757-883fe1865fb6"),
                            CreateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(5624),
                            Description = "Quyền xem mọi tài liệu trong hệ thống ",
                            Name = "VIEW_ANY_DOCUMENT",
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(5733)
                        },
                        new
                        {
                            Id = new Guid("e72214a0-24bc-471a-aca5-d897f4da0aad"),
                            CreateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(5816),
                            Description = "Quyền xem tài liệu thuộc phòng ban của mình.",
                            Name = "VIEW_OWN_DEPARTMENT_DOCUMENT",
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(5817)
                        },
                        new
                        {
                            Id = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            CreateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(5819),
                            Description = "Quyền xem tài liệu của mình.",
                            Name = "VIEW_DEPARTMENT_DOCUMENT",
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(5819)
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f"),
                            CreateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(7962),
                            Description = "Member",
                            RoleName = "Member",
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(8050)
                        },
                        new
                        {
                            Id = new Guid("a996692c-1f5e-4458-8dcf-c2494a47b6d6"),
                            CreateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(8123),
                            Description = "Admin",
                            RoleName = "Admin",
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(8124)
                        },
                        new
                        {
                            Id = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb"),
                            CreateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(8125),
                            Description = "Manager",
                            RoleName = "Manager",
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(8126)
                        },
                        new
                        {
                            Id = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136"),
                            CreateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(8127),
                            Description = "Editor",
                            RoleName = "Editor",
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 221, DateTimeKind.Utc).AddTicks(8127)
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("013a9f0a-328d-4a51-afae-5b88fddac343"),
                            PermissionId = new Guid("3796cdb0-7c0a-4cc6-a757-883fe1865fb6"),
                            RoleId = new Guid("a996692c-1f5e-4458-8dcf-c2494a47b6d6")
                        },
                        new
                        {
                            Id = new Guid("7c8e3837-f864-47cb-9adf-03905e001002"),
                            PermissionId = new Guid("e72214a0-24bc-471a-aca5-d897f4da0aad"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb")
                        },
                        new
                        {
                            Id = new Guid("fd0cd98e-119d-48ba-9867-7650cefd39c8"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f")
                        },
                        new
                        {
                            Id = new Guid("05f54cb0-5fb9-4932-8e95-d2b32bd0de42"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136")
                        },
                        new
                        {
                            Id = new Guid("99d16ed9-63b3-485b-abc6-e88e1d7e6449"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb")
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TwoFactorMethod")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13d466ed-8a2d-414d-88c0-9c7adcac2616"),
                            CreatAt = new DateTime(2025, 6, 18, 11, 13, 26, 244, DateTimeKind.Utc).AddTicks(8189),
                            Email = "admin@gmail.com",
                            FullName = "Admin",
                            Password = "gMTHtekzIhbeHPv6xtJvqE9EFueAQ5ru99SvzyDmeXSzt/dOKvgiy8KdtmHMdKir",
                            Phone = "0847911068",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 244, DateTimeKind.Utc).AddTicks(8417),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("595dd357-aaec-455e-9fa7-4fc88d4b819c"),
                            CreatAt = new DateTime(2025, 6, 18, 11, 13, 26, 263, DateTimeKind.Utc).AddTicks(4051),
                            Email = "manager@gmail.com",
                            FullName = "Manager",
                            Password = "g4MLMebanPnPBgWf9bAs9VnApl2dGgD7bmlJSzQ1DvBzrrpkTe+5kiVq5qoVmLCm",
                            Phone = "0123456789",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 263, DateTimeKind.Utc).AddTicks(4057),
                            UserName = "manager"
                        },
                        new
                        {
                            Id = new Guid("fd05266c-baf5-49bb-a846-554461bcc411"),
                            CreatAt = new DateTime(2025, 6, 18, 11, 13, 26, 281, DateTimeKind.Utc).AddTicks(9414),
                            Email = "member@gmail.com",
                            FullName = "Member",
                            Password = "0YywcDKKggnOfD5eiHC/qMZ6OY5JIR8Aabcg3WiczvxHDfLYpMo8S6+enM37D2Hn",
                            Phone = "0123456789",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 281, DateTimeKind.Utc).AddTicks(9421),
                            UserName = "member"
                        },
                        new
                        {
                            Id = new Guid("5c49c1cb-719e-42eb-8028-f2eb3eaea4cd"),
                            CreatAt = new DateTime(2025, 6, 18, 11, 13, 26, 300, DateTimeKind.Utc).AddTicks(1775),
                            Email = "editor@gmail.com",
                            FullName = "Member1",
                            Password = "lIyv321NZsWbEAKGZ3AL4xKPtD+riDn0dY0dr71xOEmPp4s6ax03I/BqNXLEq9jZ",
                            Phone = "0123456789",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "Email",
                            UpdateAt = new DateTime(2025, 6, 18, 11, 13, 26, 300, DateTimeKind.Utc).AddTicks(1780),
                            UserName = "editor"
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.UserDepartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDepartmentHead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDepartments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a60e61c-2ad5-4c60-abd2-c189eb38779a"),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            IsDepartmentHead = true,
                            UserId = new Guid("595dd357-aaec-455e-9fa7-4fc88d4b819c")
                        },
                        new
                        {
                            Id = new Guid("9951e8a8-d4f2-48dc-a9fa-37a466226ce8"),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            IsDepartmentHead = false,
                            UserId = new Guid("5c49c1cb-719e-42eb-8028-f2eb3eaea4cd")
                        },
                        new
                        {
                            Id = new Guid("d7b046e2-5fe3-4ce4-aa0b-1182feb04f54"),
                            DepartmentId = new Guid("86deff8b-cb4b-4daf-88d4-6f366b051836"),
                            IsDepartmentHead = false,
                            UserId = new Guid("fd05266c-baf5-49bb-a846-554461bcc411")
                        },
                        new
                        {
                            Id = new Guid("9b65b3e7-7985-4aae-86cf-bc8b625e6d38"),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            IsDepartmentHead = false,
                            UserId = new Guid("fd05266c-baf5-49bb-a846-554461bcc411")
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("691565e3-1c09-4789-9f96-631c654e2f23"),
                            RoleId = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136"),
                            UserId = new Guid("5c49c1cb-719e-42eb-8028-f2eb3eaea4cd")
                        },
                        new
                        {
                            Id = new Guid("46170431-f2ed-4423-a73c-270cf206fa3a"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb"),
                            UserId = new Guid("595dd357-aaec-455e-9fa7-4fc88d4b819c")
                        },
                        new
                        {
                            Id = new Guid("15731756-347d-4812-bff7-18fb43895bd6"),
                            RoleId = new Guid("a996692c-1f5e-4458-8dcf-c2494a47b6d6"),
                            UserId = new Guid("13d466ed-8a2d-414d-88c0-9c7adcac2616")
                        },
                        new
                        {
                            Id = new Guid("79c13a86-cd80-40d4-aee5-f40172d2fc1d"),
                            RoleId = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f"),
                            UserId = new Guid("fd05266c-baf5-49bb-a846-554461bcc411")
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.DepartmentRolePermission", b =>
                {
                    b.HasOne("Auth.Domain.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.User", "User")
                        .WithMany("DepartmentRolePermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Permission");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Auth.Domain.Models.RolePermission", b =>
                {
                    b.HasOne("Auth.Domain.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Auth.Domain.Models.UserDepartment", b =>
                {
                    b.HasOne("Auth.Domain.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.User", "User")
                        .WithMany("UserDepartments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Auth.Domain.Models.UserRole", b =>
                {
                    b.HasOne("Auth.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Auth.Domain.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Auth.Domain.Models.User", b =>
                {
                    b.Navigation("DepartmentRolePermissions");

                    b.Navigation("UserDepartments");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
