// <auto-generated />
using System;
using Auth.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Auth.Domain.Migrations
{
    [DbContext(typeof(DocAIAuthContext))]
    partial class DocAIAuthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auth.Domain.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            CreateAt = new DateTime(2025, 7, 9, 6, 48, 28, 468, DateTimeKind.Utc).AddTicks(4958),
                            Description = "DepartentA",
                            Name = "DepartentA",
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 468, DateTimeKind.Utc).AddTicks(5081)
                        },
                        new
                        {
                            Id = new Guid("d8854d21-8fae-46aa-b51b-0de060b92ee3"),
                            CreateAt = new DateTime(2025, 7, 9, 6, 48, 28, 468, DateTimeKind.Utc).AddTicks(5208),
                            Description = "Company",
                            Name = "Company",
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 468, DateTimeKind.Utc).AddTicks(5208)
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3796cdb0-7c0a-4cc6-a757-883fe1865fb6"),
                            CreateAt = new DateTime(2025, 7, 9, 6, 48, 28, 469, DateTimeKind.Utc).AddTicks(2061),
                            Description = "Quyền xem mọi tài liệu trong hệ thống ",
                            Name = "VIEW_ANY_DOCUMENT",
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 469, DateTimeKind.Utc).AddTicks(2173)
                        },
                        new
                        {
                            Id = new Guid("e72214a0-24bc-471a-aca5-d897f4da0aad"),
                            CreateAt = new DateTime(2025, 7, 9, 6, 48, 28, 469, DateTimeKind.Utc).AddTicks(2343),
                            Description = "Quyền xem tài liệu thuộc phòng ban của mình.",
                            Name = "VIEW_OWN_DEPARTMENT_DOCUMENT",
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 469, DateTimeKind.Utc).AddTicks(2344)
                        },
                        new
                        {
                            Id = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            CreateAt = new DateTime(2025, 7, 9, 6, 48, 28, 469, DateTimeKind.Utc).AddTicks(2346),
                            Description = "Quyền xem tài liệu của mình.",
                            Name = "VIEW_DEPARTMENT_DOCUMENT",
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 469, DateTimeKind.Utc).AddTicks(2346)
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f"),
                            CreateAt = new DateTime(2025, 7, 9, 6, 48, 28, 469, DateTimeKind.Utc).AddTicks(4793),
                            Description = "Employee",
                            RoleName = "Employee",
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 469, DateTimeKind.Utc).AddTicks(4892)
                        },
                        new
                        {
                            Id = new Guid("a996692c-1f5e-4458-8dcf-c2494a47b6d6"),
                            CreateAt = new DateTime(2025, 7, 9, 6, 48, 28, 469, DateTimeKind.Utc).AddTicks(5018),
                            Description = "Admin",
                            RoleName = "Admin",
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 469, DateTimeKind.Utc).AddTicks(5019)
                        },
                        new
                        {
                            Id = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb"),
                            CreateAt = new DateTime(2025, 7, 9, 6, 48, 28, 469, DateTimeKind.Utc).AddTicks(5021),
                            Description = "Manager",
                            RoleName = "Manager",
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 469, DateTimeKind.Utc).AddTicks(5021)
                        },
                        new
                        {
                            Id = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136"),
                            CreateAt = new DateTime(2025, 7, 9, 6, 48, 28, 469, DateTimeKind.Utc).AddTicks(5023),
                            Description = "Editor",
                            RoleName = "Editor",
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 469, DateTimeKind.Utc).AddTicks(5023)
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1014f444-b3de-4db8-9410-9c362a38f2db"),
                            PermissionId = new Guid("3796cdb0-7c0a-4cc6-a757-883fe1865fb6"),
                            RoleId = new Guid("a996692c-1f5e-4458-8dcf-c2494a47b6d6")
                        },
                        new
                        {
                            Id = new Guid("d4a7f8e1-5571-46e5-b3b2-2ee79d408f2a"),
                            PermissionId = new Guid("e72214a0-24bc-471a-aca5-d897f4da0aad"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb")
                        },
                        new
                        {
                            Id = new Guid("17566104-3004-4663-a242-a1770d65d5c6"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f")
                        },
                        new
                        {
                            Id = new Guid("33bb5518-3383-46fb-91a5-01f95d3793c6"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136")
                        },
                        new
                        {
                            Id = new Guid("0843307d-cf05-414b-84ab-394f884f4b45"),
                            PermissionId = new Guid("febebe25-dd94-4ba1-bdbd-810e4503bccd"),
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb")
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13d466ed-8a2d-414d-88c0-9c7adcac2616"),
                            Active = false,
                            CreatAt = new DateTime(2025, 7, 9, 6, 48, 28, 495, DateTimeKind.Utc).AddTicks(9028),
                            DepartmentId = new Guid("d8854d21-8fae-46aa-b51b-0de060b92ee3"),
                            Email = "admin@gmail.com",
                            FullName = "Admin",
                            Password = "zbr+GIjiZexQYo70lTjQuXndqIJ+tu3g1V4z2TE91VgXJ/u0fFqN1VGmxZgd5aUU",
                            Phone = "0847911068",
                            RoleId = new Guid("a996692c-1f5e-4458-8dcf-c2494a47b6d6"),
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 495, DateTimeKind.Utc).AddTicks(9144),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("595dd357-aaec-455e-9fa7-4fc88d4b819c"),
                            Active = false,
                            CreatAt = new DateTime(2025, 7, 9, 6, 48, 28, 516, DateTimeKind.Utc).AddTicks(4714),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            Email = "manager@gmail.com",
                            FullName = "Manager",
                            Password = "sh4ehkewlS3cFVYuqkKrFMLj+fN000U9OFusoTdINQFY8XBUrUC5Uv5NEv2EQphV",
                            Phone = "0123456789",
                            RoleId = new Guid("a5ddf431-aae9-4d9f-8d61-1a37776bb4bb"),
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 516, DateTimeKind.Utc).AddTicks(4719),
                            UserName = "manager"
                        },
                        new
                        {
                            Id = new Guid("fd05266c-baf5-49bb-a846-554461bcc411"),
                            Active = false,
                            CreatAt = new DateTime(2025, 7, 9, 6, 48, 28, 536, DateTimeKind.Utc).AddTicks(6481),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            Email = "employee@gmail.com",
                            FullName = "Employee",
                            Password = "XwnHf6qw79crCIIBreZro5bRr0EHlndsBYrpBowqLoBfQdUHxwZRLkwulIbobrXi",
                            Phone = "0123456789",
                            RoleId = new Guid("4e29a870-9131-4cc2-97ca-eaa748b5f17f"),
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 536, DateTimeKind.Utc).AddTicks(6486),
                            UserName = "employee"
                        },
                        new
                        {
                            Id = new Guid("5c49c1cb-719e-42eb-8028-f2eb3eaea4cd"),
                            Active = false,
                            CreatAt = new DateTime(2025, 7, 9, 6, 48, 28, 556, DateTimeKind.Utc).AddTicks(8304),
                            DepartmentId = new Guid("8bf13891-1ce9-405c-add9-0ada93308671"),
                            Email = "editor@gmail.com",
                            FullName = "Editor",
                            Password = "ZWsFN7GneikIvlo6nENDWv0HN2klxOgnXjQ6bVsMwnSOoEIC8n4GPXY2RqyPlaPK",
                            Phone = "0123456789",
                            RoleId = new Guid("8e7d55e4-67d3-4b73-9995-21b163493136"),
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 556, DateTimeKind.Utc).AddTicks(8310),
                            UserName = "editor"
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.UserSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TwoFactorMethod")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ddfcbea3-56e9-4187-97f6-521ca24c2412"),
                            NotificationsEnabled = true,
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "email",
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 557, DateTimeKind.Utc).AddTicks(3524),
                            UserId = new Guid("13d466ed-8a2d-414d-88c0-9c7adcac2616")
                        },
                        new
                        {
                            Id = new Guid("dd9105eb-4df0-4c32-bc55-fd0169e386fc"),
                            NotificationsEnabled = true,
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "email",
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 557, DateTimeKind.Utc).AddTicks(3791),
                            UserId = new Guid("595dd357-aaec-455e-9fa7-4fc88d4b819c")
                        },
                        new
                        {
                            Id = new Guid("86254802-1d1e-4734-a25b-ef22ff39cefc"),
                            NotificationsEnabled = true,
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "email",
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 557, DateTimeKind.Utc).AddTicks(3794),
                            UserId = new Guid("fd05266c-baf5-49bb-a846-554461bcc411")
                        },
                        new
                        {
                            Id = new Guid("4e8bff21-b470-4b9e-92da-400d21992f96"),
                            NotificationsEnabled = true,
                            TwoFactorEnabled = false,
                            TwoFactorMethod = "email",
                            UpdateAt = new DateTime(2025, 7, 9, 6, 48, 28, 557, DateTimeKind.Utc).AddTicks(3796),
                            UserId = new Guid("5c49c1cb-719e-42eb-8028-f2eb3eaea4cd")
                        });
                });

            modelBuilder.Entity("Auth.Domain.Models.RolePermission", b =>
                {
                    b.HasOne("Auth.Domain.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Auth.Domain.Models.User", b =>
                {
                    b.HasOne("Auth.Domain.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Auth.Domain.Models.UserSetting", b =>
                {
                    b.HasOne("Auth.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Auth.Domain.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
