services:
  ai.api:
    image: magicflexing/docai-ai-api:latest
    ports:
      - "5003:5003"
    restart: always

  auth.api:
    image: magicflexing/docai-auth-api:latest
    ports:
      - "5001:5001"
    restart: always

  # API Gateway Instance 1
  apigateway1:
    image: magicflexing/docai-gateway:latest
    ports:
      - "5000:5000" # Ánh xạ cổng 5000 của container ra cổng 5000 của host
    restart: always

  # API Gateway Instance 2
  apigateway2:
    image: magicflexing/docai-gateway:latest
    ports:
      - "5005:5000" # Ánh xạ cổng 5000 của container ra cổng 5005 của host
    restart: always

  document.api:
    image: magicflexing/docai-document-api:latest
    ports:
      - "5002:5002"
    restart: always

  notification.api:
    image: magicflexing/docai-notification-api:latest
    ports:
      - "5004:5004"
    restart: always


#  apphost:
#    image: magicflexing/docai-apphost:latest
#    ports:
#      - "5005:8080"

